src/main/java/edu/iit/sat/itmd4515/dwadekar/fp/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.dwadekar.fp.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 * Used for controlling Login into application
 *
 * @author dwadekar
 */
@Named
@RequestScoped
public class LoginController extends AbstractJSFController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotNull(message = "Please enter the username")
    private String username;
    @NotNull(message = "Please enter the password")
    private String password;

    /**
     * Default Constructor
     */
    public LoginController() {
    }

    /**
     * Post Construct Method
     */
    @Override
    @PostConstruct
    protected void postConstruct() {
        super.postConstruct();
    }

    /**
     * Returns the User name
     *
     * @return
     */
    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    /**
     * Check whether Administrator user is logged in
     *
     * @return
     */
    public boolean isAdmin() {
        return facesContext.getExternalContext().isUserInRole("ADMINS");
    }

    /**
     * Check whether Employee user is logged in
     *
     * @return
     */
    public boolean isEmployee() {
        return facesContext.getExternalContext().isUserInRole("EMPLOYEE");
    }

    /**
     * Check whether Customer user is logged in
     *
     * @return
     */
    public boolean isCustomer() {
        return facesContext.getExternalContext().isUserInRole("CUSTOMER");
    }

    /**
     * Check the role of user
     *
     * @param path
     * @return
     */
    public String getRoleContextPath(String path) {
        if (isAdmin()) {
            return "/admin/" + path + FACES_REDIRECT;
        } else if (isEmployee()) {
            return "/employeePortal/" + path + FACES_REDIRECT;
        } else if (isCustomer()) {
            return "/customerPortal/" + path + FACES_REDIRECT;
        }

        return path;
    }

    /**
     * Method to do login into application
     *
     * @return
     */
    public String doLogin() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "You have entered a bad username or password."));
            return "login.xhtml";
        }
        return getRoleContextPath("welcome.xhtml");
    }

    /**
     * Method to do logout into application
     *
     * @return
     */
    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username);
            facesContext.addMessage(null, new FacesMessage("Bad Logout"));
            return "login.xhtml";
        }
        return "/login.xhtml";
    }

    /**
     * Method to redirect to login page
     *
     * @return
     */
    public String redirectLogin() {
        return "login.xhtml";
    }

    /**
     * Returns the username
     *
     * @return
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the username
     *
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password of user
     *
     * @return
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password of user
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/admin/createUserLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">
        Create User Login
    </ui:define>

    <ui:define name="content">
        <h:form class="form-horizontal">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home"><b>Employee Profile Information</b></a></li>
            </ul>
            <br></br>
            <div class="tab-content">
                <div id="home" class="tab-pane fade in active">
                    <div class="row test">
                        <h:panelGroup class="form-group" layout="block">
                            <h:outputLabel styleClass="control-label col-sm-2 text-left" for="username" value="Username " ><span style="color: red;">* </span>:</h:outputLabel>
                            <div class="col-sm-10">
                                <h:inputText class="form-control" id="username" value="#{adminController.user.userName}" required="true" requiredMessage="Please enter username" p:placeholder="Enter Username" />
                                <h:message for="username" style="color: red"/>
                            </div>
                        </h:panelGroup>
                        <h:panelGroup class="form-group" layout="block">
                            <h:outputLabel styleClass="control-label col-sm-2 text-left" for="fullName" value="Full Name "><span style="color: red;">* </span>:</h:outputLabel>
                            <div class="col-sm-10">
                                <h:inputText class="form-control" id="fullName" value="#{adminController.user.nameOfUser}" required="true" requiredMessage="Please enter full name of user" p:placeholder="Enter full name of user" />
                                <h:message for="fullName" style="color: red"/>
                            </div>
                        </h:panelGroup>
                        <h:panelGroup class="form-group" layout="block">
                            <h:outputLabel styleClass="control-label col-sm-2 text-left" for="emailAddress" value="Email Address "><span style="color: red;">* </span>:</h:outputLabel>
                            <div class="col-sm-10">
                                <h:inputText class="form-control" id="emailAddress" value="#{adminController.user.emailID}" required="true" requiredMessage="Please enter Email Address" validatorMessage="Invalid Email Format" p:placeholder="Enter Email Address" >
                                    <f:validateRegex pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                                </h:inputText>
                                <h:message for="emailAddress" style="color: red"/>
                            </div>
                        </h:panelGroup>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#group"><b>Group Information</b></a></li>
            </ul>
            <br></br>
            <div class="tab-content">
                <div id="group" class="tab-pane fade in active">
                    <div class="row test">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="groupName" value="Group Name "><span style="color: red;">* </span>:</h:outputLabel>
                        <div class="col-sm-10">
                            <h:selectOneMenu class="form-control" id="groupName" value="#{adminController.group.groupName}" required="true" requiredMessage="Please select group of user">
                                <f:selectItems value="#{adminController.groupList}" var="grp" itemValue="#{grp.groupName}" itemLabel="#{grp.groupName}"/>
                            </h:selectOneMenu>
                            <h:message for="groupName" style="color: red"/>
                        </div>
                    </div>
                </div>
            </div>
            <br></br>
            <h:panelGroup style="display:block; text-align:center">
                <h:commandButton styleClass="btn btn-primary" action="#{adminController.executeCreateUser()}" value="Create" />
                &nbsp;&nbsp;&nbsp;
                <h:commandButton styleClass="btn btn-primary" type="reset" value="Reset" />
            </h:panelGroup>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/admin/editAdminLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">
        Edit Administrator Login Profile
    </ui:define>

    <ui:define name="content">
        <h:form class="form-horizontal">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home"><b>Administrator Login Information</b></a></li>
            </ul>
            <div class="tab-content">
                <div id="home" class="tab-pane fade in active">
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="adminRefID" value="Admin Reference ID :" />
                        <h:outputText styleClass="col-sm-2 text-left" value="#{adminController.adminUser.id}"/>
                        <h:inputHidden id="adminRefID" value="#{adminController.adminUser.id}" />
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="adminUserName" value="Admin User Name :"/>
                        <h:outputText styleClass="col-sm-2 text-left" value="#{adminController.user.userName}"/>
                        <h:inputHidden id="adminUserName" value="#{adminController.user.userName}" />
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="adminName" value="Customer Name "><span style="color: red;">* </span>:</h:outputLabel>
                        <div class="col-sm-10">
                            <h:inputText class="form-control" id="adminName" value="#{adminController.user.nameOfUser}" required="true" requiredMessage="Please enter full name of user" p:placeholder="Enter full name of user" />
                            <h:message for="adminName" style="color: red"/>
                        </div>
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="emailID" value="Email Address "><span style="color: red;">* </span>:</h:outputLabel>
                        <div class="col-sm-10">
                            <h:inputText class="form-control" id="emailID" value="#{adminController.user.emailID}" required="true" requiredMessage="Please enter Email Address" validatorMessage="Invalid Email Format" p:placeholder="Enter Email Address" >
                                <f:validateRegex pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                            </h:inputText>
                            <h:message for="emailID" style="color: red"/>
                        </div>
                    </h:panelGroup>
                </div>
            </div>
            <h:panelGroup style="display:block; text-align:center">
                <h:commandButton styleClass="btn btn-primary" action="#{adminController.executeUpdateAdmin()}" value="Update" />
                &nbsp;&nbsp;&nbsp;
                <h:commandButton styleClass="btn btn-primary" type="reset" value="Reset" />
            </h:panelGroup>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/admin/editEmployeeLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">
        Edit Employee Login Profile
    </ui:define>

    <ui:define name="content">
        <h:form class="form-horizontal">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#home"><b>Employee Login Information</b></a></li>
            </ul>
            <div class="tab-content">
                <div id="home" class="tab-pane fade in active">
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="empRefID" value="Reference ID :" />
                        <h:outputText styleClass="col-sm-2 text-left" value="#{adminController.employee.id}"/>
                        <h:inputHidden id="empRefID" value="#{adminController.employee.id}" />
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="empUserName" value="Employee User Name :"/>
                        <h:outputText styleClass="col-sm-2 text-left" value="#{adminController.user.userName}"/>
                        <h:inputHidden id="empUserName" value="#{adminController.user.userName}" />
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="empName" value="Employee Name "><span style="color: red;">* </span>:</h:outputLabel>
                        <div class="col-sm-10">
                            <h:inputText class="form-control" id="empName" value="#{adminController.user.nameOfUser}" required="true" requiredMessage="Please enter full name of user" p:placeholder="Enter full name of user" />
                            <h:message for="empName" style="color: red"/>
                        </div>
                    </h:panelGroup>
                    <h:panelGroup class="form-group" layout="block">
                        <h:outputLabel styleClass="control-label col-sm-2 text-left" for="emailID" value="Email Address "><span style="color: red;">* </span>:</h:outputLabel>
                        <div class="col-sm-10">
                            <h:inputText class="form-control" id="emailID" value="#{adminController.user.emailID}" required="true" requiredMessage="Please enter Email Address" validatorMessage="Invalid Email Format" p:placeholder="Enter Email Address">
                                <f:validateRegex pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                            </h:inputText>
                            <h:message for="emailID" style="color: red"/>
                        </div>
                    </h:panelGroup>
                </div>
            </div>
            <h:panelGroup style="display:block; text-align:center">
                <h:commandButton styleClass="btn btn-primary" action="#{adminController.executeUpdateEmployee()}" value="Update" />
                &nbsp;&nbsp;&nbsp;
                <h:commandButton styleClass="btn btn-primary" type="reset" value="Reset" />
            </h:panelGroup>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/admin/errorCreateUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        Error
    </ui:define>

    <ui:define name="content">
        Sorry!! User profile <b style="color: red"><h:outputText value="#{adminController.user.userName}"/></b> already exists.
    </ui:define>

</ui:composition>

src/main/webapp/admin/successCreateUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/adminTemplate.xhtml">

    <ui:define name="title">
        Successful User Login Creation
    </ui:define>

    <ui:define name="content">
        The User Login profile have been successfully created.
    </ui:define>

</ui:composition>

src/main/webapp/admin/successCustDelete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/adminTemplate.xhtml">

    <ui:define name="title">
        Successful Customer deletion
    </ui:define>

    <ui:define name="content">
        The selected Customer ID is deleted successfully.
    </ui:define>

</ui:composition>

src/main/webapp/admin/successEmpDelete.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/adminTemplate.xhtml">

    <ui:define name="title">
        Successful Employee deletion
    </ui:define>

    <ui:define name="content">
        The selected Employee ID is deleted successfully.
    </ui:define>

</ui:composition>

src/main/webapp/admin/successUpdateCustomer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/adminTemplate.xhtml">

    <ui:define name="title">
        Successful Updation of Customer Profile
    </ui:define>

    <ui:define name="content">
        The Customer Profile has been successfully updated.
    </ui:define>

</ui:composition>

src/main/webapp/admin/viewAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        View Administrator Login Information
    </ui:define>

    <ui:define name="content">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home"><b>Administrator Login Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="row test">
                    <div class="col-md-4">
                        <p>Admin Reference ID</p>
                        <p>Admin User Name</p>
                        <p>Admin Name</p>
                        <p>Email Address</p>
                        <p>Date of Creation</p>
                    </div>
                    <div class="col-md-4">
                        <p><h:outputText value="#{adminController.adminUser.id}"/></p>
                        <p><h:outputText value="#{adminController.adminUser.user.userName}"/></p>
                        <p><h:outputText value="#{adminController.adminUser.user.nameOfUser}"/></p>
                        <p><h:outputText value="#{adminController.adminUser.user.emailID}"/></p>
                        <p><h:outputText value="#{adminController.adminUser.creationDate}"><f:convertDateTime type="date"/></h:outputText></p>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#empGrp"><b>Administrator Group Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="empGrp" class="tab-pane fade in active">
                <div class="row test">
                    <h:dataTable class="table table-hover table-striped" value="#{adminController.adminUser.user.userGroups}" var="group">
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupName}"></h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupDescription}"></h:outputText>
                        </h:column>
                    </h:dataTable>
                </div>
            </div>
        </div>
    </ui:define>

</ui:composition>

src/main/webapp/admin/viewAdmins.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        Administrator's Login Information
    </ui:define>

    <ui:define name="content">
        <h:dataTable class="table table-hover table-striped" value="#{adminController.adminList}" var="admin">
            <h:column>
                <f:facet name="header"><h:outputText value="Admin Reference ID"/></f:facet>
                <h:outputText value="#{admin.id}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Admin User Name"/></f:facet>
                <h:outputText value="#{admin.user.userName}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Date of Creation"/></f:facet>
                <h:outputText value="#{admin.creationDate}"><f:convertDateTime type="date"/></h:outputText>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{adminController.doShowAdmin(admin)}" value="Show"/></h:form>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{adminController.doUpdateAdmin(admin)}" value="Update"/></h:form>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{adminController.doDeleteAdmin(admin)}" value="Delete"/></h:form>
            </h:column>
        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/admin/viewCustomer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        View Customer Login Information
    </ui:define>

    <ui:define name="content">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home"><b>Customer Login Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="row test">
                    <div class="col-md-4">
                        <p>Customer Reference ID</p>
                        <p>Customer Username</p>
                        <p>Customer Name</p>
                        <p>Email Address</p>
                        <p>Date of Creation</p>
                    </div>
                    <div class="col-md-4">
                        <p><h:outputText value="#{adminController.customer.id}"/></p>
                        <p><h:outputText value="#{adminController.customer.user.userName}"/></p>
                        <p><h:outputText value="#{adminController.customer.user.nameOfUser}"/></p>
                        <p><h:outputText value="#{adminController.customer.user.emailID}"/></p>
                        <p><h:outputText value="#{adminController.customer.creationDate}"><f:convertDateTime type="date"/></h:outputText></p>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#custGrp"><b>Customer Group Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="custGrp" class="tab-pane fade in active">
                <div class="row test">
                    <h:dataTable class="table table-hover table-striped" value="#{adminController.customer.user.userGroups}" var="group">
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupName}"></h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupDescription}"></h:outputText>
                        </h:column>
                    </h:dataTable>
                </div>
            </div>
        </div>
    </ui:define>

</ui:composition>

src/main/webapp/admin/viewEmployee.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/adminTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        View Employee Login Information
    </ui:define>

    <ui:define name="content">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home"><b>Employee Login Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="row test">
                    <div class="col-md-4">
                        <p>Employee Reference ID</p>
                        <p>Employee User Name</p>
                        <p>Employee Name</p>
                        <p>Email Address</p>
                        <p>Date of Creation</p>
                    </div>
                    <div class="col-md-4">
                        <p><h:outputText value="#{adminController.employee.id}"/></p>
                        <p><h:outputText value="#{adminController.employee.user.userName}"/></p>
                        <p><h:outputText value="#{adminController.employee.user.nameOfUser}"/></p>
                        <p><h:outputText value="#{adminController.employee.user.emailID}"/></p>
                        <p><h:outputText value="#{adminController.employee.creationDate}"><f:convertDateTime type="date"/></h:outputText></p>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#empGrp"><b>Employee Group Information</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="empGrp" class="tab-pane fade in active">
                <div class="row test">
                    <h:dataTable class="table table-hover table-striped" value="#{adminController.employee.user.userGroups}" var="group">
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupName}"></h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="Group Name"/></f:facet>
                            <h:outputText value="#{group.groupDescription}"></h:outputText>
                        </h:column>
                    </h:dataTable>
                </div>
            </div>
        </div>
    </ui:define>

</ui:composition>