src/main/java/edu/iit/sat/itmd4515/dwadekar/fp/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.dwadekar.fp.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 * Used for controlling Login into application
 *
 * @author dwadekar
 */
@Named
@RequestScoped
public class LoginController extends AbstractJSFController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotNull(message = "Please enter the username")
    private String username;
    @NotNull(message = "Please enter the password")
    private String password;

    /**
     * Default Constructor
     */
    public LoginController() {
    }

    /**
     * Post Construct Method
     */
    @Override
    @PostConstruct
    protected void postConstruct() {
        super.postConstruct();
    }

    /**
     * Returns the User name
     *
     * @return
     */
    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    /**
     * Check whether Administrator user is logged in
     *
     * @return
     */
    public boolean isAdmin() {
        return facesContext.getExternalContext().isUserInRole("ADMINS");
    }

    /**
     * Check whether Employee user is logged in
     *
     * @return
     */
    public boolean isEmployee() {
        return facesContext.getExternalContext().isUserInRole("EMPLOYEE");
    }

    /**
     * Check whether Customer user is logged in
     *
     * @return
     */
    public boolean isCustomer() {
        return facesContext.getExternalContext().isUserInRole("CUSTOMER");
    }

    /**
     * Check the role of user
     *
     * @param path
     * @return
     */
    public String getRoleContextPath(String path) {
        if (isAdmin()) {
            return "/admin/" + path + FACES_REDIRECT;
        } else if (isEmployee()) {
            return "/employeePortal/" + path + FACES_REDIRECT;
        } else if (isCustomer()) {
            return "/customerPortal/" + path + FACES_REDIRECT;
        }

        return path;
    }

    /**
     * Method to do login into application
     *
     * @return
     */
    public String doLogin() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "You have entered a bad username or password."));
            return "login.xhtml";
        }
        return getRoleContextPath("welcome.xhtml");
    }

    /**
     * Method to do logout into application
     *
     * @return
     */
    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();
        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username);
            facesContext.addMessage(null, new FacesMessage("Bad Logout"));
            return "login.xhtml";
        }
        return "/login.xhtml";
    }

    /**
     * Method to redirect to login page
     *
     * @return
     */
    public String redirectLogin() {
        return "login.xhtml";
    }

    /**
     * Returns the username
     *
     * @return
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the username
     *
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password of user
     *
     * @return
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password of user
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/customerPortal/errorPerformTxn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml">

    <ui:define name="title">
        Error
    </ui:define>

    <ui:define name="content">
        <b style="color: red">Sorry!! No account found for performing transaction.</b>
        <br/><br/>
        Please contact Bank representive for account creation.
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/errorTxn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml">

    <ui:define name="title">
        Error
    </ui:define>

    <ui:define name="content">
        Sorry!! Available Balance in account is not sufficient. Please contact bank representative for this.
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/performTransactions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Perform Transactions in an Account
    </ui:define>

    <ui:define name="content">
        <h:dataTable class="table table-hover table-striped" value="#{customerInfoController.accountList}" var="account">
            <h:column>
                <f:facet name="header"><h:outputText value="Account ID"/></f:facet>
                <h:outputText value="#{account.id}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Number"/></f:facet>
                <h:outputText value="#{account.accountNo}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Customer ID"/></f:facet>
                <h:outputText value="#{account.customerID}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Type"/></f:facet>
                <h:outputText value="#{account.accountType}"/>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{customerInfoController.doPerformTransaction(account)}" value="Perform Transaction"/></h:form>
            </h:column>
        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/performTxn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="title">
        Perform Transaction
    </ui:define>

    <ui:define name="content">
        <h:form class="form-horizontal">
            <h:panelGroup layout="block" class="form-group">
                <h:inputHidden id="accountID" value="#{customerInfoController.accountInfo.id}" />
            </h:panelGroup>
            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel for="accountNo" value="Account No: #{customerInfoController.accountInfo.accountNo}" />
                <h:inputHidden id="accountNo" value="#{customerInfoController.accountInfo.accountNo}" />
            </h:panelGroup>
            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel for="amtBalance" value="Available Balance: #{customerInfoController.accountInfo.availableBalance}" />
                <h:inputHidden id="amtBalance" value="#{customerInfoController.accountInfo.availableBalance}" />
            </h:panelGroup>
            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel for="modeOfTxn" value="Mode of Transaction "><span style="color: red;">* </span>:</h:outputLabel>
                <h:selectOneMenu class="form-control" id="modeOfTxn" value="#{customerInfoController.txnByCust.modeOfTxn}" required="true" requiredMessage="Please select mode of txn">
                    <f:selectItem itemValue="ATM Withdrawal" itemLabel="ATM Withdrawal" />
                    <f:selectItem itemValue="RTGS Transfer" itemLabel="RTGS Transfer" />
                </h:selectOneMenu>
                <h:message for="modeOfTxn" style="color: red"/>
            </h:panelGroup>
            <h:panelGroup layout="block" class="form-group">
                <h:outputLabel for="amountOfTxn" value="Amount "><span style="color: red;">* </span>:</h:outputLabel>
                <h:inputText class="form-control" id="amountOfTxn" value="#{customerInfoController.txnByCust.amount}" required="true" requiredMessage="Please enter transaction amount" p:placeholder="Transaction Amount"/>
                <h:message for="amountOfTxn" style="color: red"/>
            </h:panelGroup>
            <h:panelGroup style="display:block; text-align:center">
                <h:commandButton styleClass="btn btn-primary" action="#{customerInfoController.executeTransaction()}" value="Transmit" />
                &nbsp;&nbsp;&nbsp;
                <h:commandButton styleClass="btn btn-primary" type="reset" value="Reset" />
            </h:panelGroup>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/success.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Successful Transaction
    </ui:define>

    <ui:define name="content">
        Successfully Transaction completed. The details of Transactions are as follows:
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home"><b>Transaction Summary</b></a></li>
        </ul>
        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div class="row test">
                    <div class="col-md-4">
                        <p>Customer ID :</p>
                        <p>Account No :</p>
                        <p>Account Type :</p>
                        <p>Transaction Amount :</p>
                        <p>Total Available Balance :</p>
                    </div>
                    <div class="col-md-4">
                        <p><h:outputText value="#{customerInfoController.customer.id}"/></p>
                        <p><h:outputText value="#{customerInfoController.newAccountInfo.accountNo}"/></p>
                        <p><h:outputText value="#{customerInfoController.newAccountInfo.accountType}"/></p>
                        <p>
                            <h:outputText value="#{customerInfoController.newAccountInfo.currency}"/><h:outputText value=" "/>
                            <h:outputText value="#{customerInfoController.newTransaction.amount}"/>
                        </p>
                        <p>
                            <h:outputText value="#{customerInfoController.newAccountInfo.currency}"/><h:outputText value=" "/>
                            <h:outputText value="#{customerInfoController.newAccountInfo.availableBalance}"/>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/viewAccountInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Account Information of Customer
    </ui:define>

    <ui:define name="content">
        <c:choose>
            <c:when test="#{customerInfoController.accountInfo == null}">
                <b style="color: red">Sorry!! No account details found for your customer login.</b>
            </c:when>
            <c:otherwise>
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home"><b>Account Information</b></a></li>
                </ul>
                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <div class="row test">
                            <div class="col-md-4">
                                <p>Customer ID</p>
                                <p>Customer Name</p>
                                <p>Account Number</p>
                                <p>Account Type</p>
                                <p>Account Currency</p>
                                <p>Available Balance</p>
                            </div>
                            <div class="col-md-4">
                                <p><h:outputText value="#{customerInfoController.customer.id}"/></p>
                                <p>
                                    <h:outputText value="#{customerInfoController.customer.title}"/><h:outputText value=" "/>
                                    <h:outputText value="#{customerInfoController.customer.firstName}"/><h:outputText value=" "/>
                                    <h:outputText value="#{customerInfoController.customer.lastName}"/>
                                </p>
                                <p><h:outputText value="#{customerInfoController.accountInfo.accountNo}"/></p>
                                <p><h:outputText value="#{customerInfoController.accountInfo.accountType}"/></p>
                                <p><h:outputText value="#{customerInfoController.accountInfo.currency}"/></p>
                                <p>
                                    <h:outputText value="#{customerInfoController.accountInfo.currency}"/><h:outputText value=" "/>
                                    <h:outputText value="#{customerInfoController.accountInfo.availableBalance}"/>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </c:otherwise>
        </c:choose>
        <h:panelGroup layout="block" class="container">

            <h:panelGroup layout="block" 
                          class="alert alert-warning alert-dismissible"
                          rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h:messages showDetail="false" globalOnly="true" showSummary="true"/>
            </h:panelGroup>

            <h:messages showDetail="true" errorStyle="color: red" warnStyle="color: orange"
                        infoStyle="color: blue" globalOnly="true" showSummary="true"/>

        </h:panelGroup>
    </ui:define>
</ui:composition>

src/main/webapp/customerPortal/viewAccounts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        View Account's of Customer
    </ui:define>

    <ui:define name="content">
        <h:dataTable class="table table-hover table-striped" value="#{customerInfoController.accountList}" var="account">
            <h:column>
                <f:facet name="header"><h:outputText value="Account ID"/></f:facet>
                <h:outputText value="#{account.id}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Number"/></f:facet>
                <h:outputText value="#{account.accountNo}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Customer ID"/></f:facet>
                <h:outputText value="#{account.customerID}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Type"/></f:facet>
                <h:outputText value="#{account.accountType}"/>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{customerInfoController.doShowAccountInfo(account)}" value="Show Account Details"/></h:form>
            </h:column>
        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/viewCustomerInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/profileTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Profile of Customer
    </ui:define>

    <ui:define name="custID"><h:outputText value="#{customerInfoController.customer.id}"/></ui:define>
    <ui:define name="custName">
        <h:outputText value="#{customerInfoController.customer.title}"/><h:outputText value=" "/>
        <h:outputText value="#{customerInfoController.customer.firstName}"/><h:outputText value=" "/>
        <h:outputText value="#{customerInfoController.customer.lastName}"/>
    </ui:define>
    <ui:define name="custRelationType"><h:outputText value="#{customerInfoController.customer.relationShipType}"/></ui:define>
    <ui:define name="custDOB"><h:outputText value="#{customerInfoController.customer.dateOfBirth}"><f:convertDateTime type="date"/></h:outputText></ui:define>
    <ui:define name="custHomeBranch"><h:outputText value="#{customerInfoController.customer.branchId}"/></ui:define>
    <ui:define name="creationDate"><h:outputText value="#{customerInfoController.customer.creationDate}"><f:convertDateTime type="date"/></h:outputText></ui:define>
    
    <ui:define name="custHouseNo"><h:outputText value="#{customerInfoController.addressInfo.houseNo}"/></ui:define>
    <ui:define name="custHouseName"><h:outputText value="#{customerInfoController.addressInfo.houseName}"/></ui:define>
    <ui:define name="custBuildingNo"><h:outputText value="#{customerInfoController.addressInfo.buildingNo}"/></ui:define>
    <ui:define name="streetName"><h:outputText value="#{customerInfoController.addressInfo.streetName}"/></ui:define>
    <ui:define name="custCityName"><h:outputText value="#{customerInfoController.addressInfo.cityName}"/></ui:define>
    <ui:define name="custTownName"><h:outputText value="#{customerInfoController.addressInfo.townName}"/></ui:define>
    <ui:define name="custCountryName"><h:outputText value="#{customerInfoController.addressInfo.countryName}"/></ui:define>
    <ui:define name="custPostalCode"><h:outputText value="#{customerInfoController.addressInfo.postalCode}"/></ui:define>
    <ui:define name="presentAddDate"><h:outputText value="#{customerInfoController.addressInfo.presentAddressDate}"><f:convertDateTime type="date"/></h:outputText></ui:define>
    
    <ui:define name="email"><h:outputText value="#{customerInfoController.contactInfo.emailAddress}"/></ui:define>
    <ui:define name="mobile"><h:outputText value="#{customerInfoController.contactInfo.mobileNumber}"/></ui:define>
    <ui:define name="telephone"><h:outputText value="#{customerInfoController.contactInfo.homeNumber}"/></ui:define>
    <ui:define name="officeNo"><h:outputText value="#{customerInfoController.contactInfo.officeNumber}"/></ui:define>
    
</ui:composition>

src/main/webapp/customerPortal/viewTransactionSummary.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Transaction Summary
    </ui:define>

    <ui:define name="content">
        <c:choose>
            <c:when test="#{customerInfoController.accountInfo == null}">
                <b style="color: red">Sorry!! No transaction details found for your customer login.</b>
            </c:when>
            <c:otherwise>
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home"><b>Account Information</b></a></li>
                </ul>
                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <div class="row test">
                            <div class="col-md-4">
                                <p>Customer ID</p>
                                <p>Customer Name</p>
                                <p>Account Number</p>
                                <p>Account Type</p>
                            </div>
                            <div class="col-md-4">
                                <p><h:outputText value="#{customerInfoController.customer.id}"/></p>
                                <p>
                                    <h:outputText value="#{customerInfoController.customer.title}"/><h:outputText value=" "/>
                                    <h:outputText value="#{customerInfoController.customer.firstName}"/><h:outputText value=" "/>
                                    <h:outputText value="#{customerInfoController.customer.lastName}"/>
                                </p>
                                <p><h:outputText value="#{customerInfoController.accountInfo.accountNo}"/></p>
                                <p><h:outputText value="#{customerInfoController.accountInfo.accountType}"/></p>
                            </div>
                        </div>
                    </div>
                </div>
                <br/><br/>
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#txn"><b>Transaction Information</b></a></li>
                </ul>
                <div class="tab-content">
                    <div id="txn" class="tab-pane fade in active">
                        <div class="row test">
                            <div class="col-md-4">
                                <h:dataTable class="table table-hover table-striped" value="#{customerInfoController.transactionList}" var="transaction">
                                    <h:column>
                                        <f:facet name="header"><h:outputText value="ID"/></f:facet>
                                        <h:outputText value="#{transaction.id}" ></h:outputText>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"><h:outputText value="Type of Transaction"/></f:facet>
                                        <h:outputText value="#{transaction.typeOfTxn}"></h:outputText>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"><h:outputText value="Mode of Transaction"/></f:facet>
                                        <h:outputText value="#{transaction.modeOfTxn}"></h:outputText>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"><h:outputText value="Amount Withdrawn"/></f:facet>
                                        <h:outputText value="#{transaction.amount}"></h:outputText>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"><h:outputText value="Date of transaction"/></f:facet>
                                        <h:outputText value="#{transaction.txnDate}">
                                            <f:convertDateTime type="date"/>
                                        </h:outputText>
                                    </h:column>
                                </h:dataTable>
                            </div>
                        </div>
                    </div>
                </div>
            </c:otherwise>
        </c:choose>
        <h:panelGroup layout="block" class="container">

            <h:panelGroup layout="block" 
                          class="alert alert-warning alert-dismissible"
                          rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h:messages showDetail="false" globalOnly="true" showSummary="true"/>
            </h:panelGroup>

            <h:messages showDetail="true" errorStyle="color: red" warnStyle="color: orange"
                        infoStyle="color: blue" globalOnly="true" showSummary="true"/>

        </h:panelGroup>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/viewTransactions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns="http://www.w3.org/1999/xhtml"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        View Transaction Summary of Account
    </ui:define>

    <ui:define name="content">
        <h:dataTable class="table table-hover table-striped" value="#{customerInfoController.accountList}" var="account">
            <h:column>
                <f:facet name="header"><h:outputText value="Account ID"/></f:facet>
                <h:outputText value="#{account.id}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Number"/></f:facet>
                <h:outputText value="#{account.accountNo}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Customer ID"/></f:facet>
                <h:outputText value="#{account.customerID}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="Account Type"/></f:facet>
                <h:outputText value="#{account.accountType}"/>
            </h:column>
            <h:column>
                <h:form><h:commandLink action="#{customerInfoController.doShowTransactionSummary(account)}" value="Enquire Transactions"/></h:form>
            </h:column>
        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/customerPortal/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="title">
        <h:outputText value="Welcome #{loginController.remoteUser}!!"/>
    </ui:define>

    <ui:define name="content">
        Welcome Nexus Banking Group's portal for Customer within our bank!!
    </ui:define>
</ui:composition>